# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#

# define multiple services here
services:
  # infrastructure
  - name: sync-api
    project: ./Sync.API/Sync.API.csproj
    bindings:
      - port: 8600
    env:
      - name: DbConnection
        value: "Server=localhost;Port=8605;User ID=user;Password=123456;Database=syncdb;Command Timeout=0;"
      - name: ASPNETCORE_ENVIRONMENT
        value: Development

  - name: sync-api-db
    image: postgres:10.3-alpine
    env:
      - name: POSTGRES_DB
        value: syncdb
      - name: POSTGRES_USER
        value: user
      - name: POSTGRES_PASSWORD
        value: 123456
    volumes:
      - name: sync-api-db-data
        target: /var/lib/postgresql/data
    bindings:
      - port: 8605
        containerPort: 5432
        connectionString: Server=${host};Port=${port};
