// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sync.DAL;

#nullable disable

namespace Sync.DAL.Migrations
{
    [DbContext(typeof(SyncDataBaseContext))]
    [Migration("20220818164108_AddTestData")]
    partial class AddTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sync.DAL.Entities.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test 1",
                            Values = " "
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test 2",
                            Values = " "
                        },
                        new
                        {
                            Id = 3,
                            Name = "Test 3",
                            Values = " "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Test 4",
                            Values = " "
                        },
                        new
                        {
                            Id = 5,
                            Name = "Test 5",
                            Values = " "
                        },
                        new
                        {
                            Id = 6,
                            Name = "Test 6",
                            Values = " "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
